
version: 2

jobs:
  build:
    docker:
      - image: 'docker:17.04-git'
    working_directory: ~/dobi
    steps:
      - checkout
      - setup_remote_docker
      # TODO: load cache
      - run: |
          set -x
          docker run -d --privileged -p 3838:3838 --name dind --rm docker:17.04-dind -H 0.0.0.0:3838
          sleep 10
          timeout -t 60 docker logs dind || true
          export DOCKER_HOST=tcp://$(echo $DOCKER_HOST | awk -F'[/:]' '{print $4}'):3838
          echo $DOCKER_HOST
          script/ci-deps
          script/ci-run

#general:
#  branches:
#    ignore: [gh-pages]

#dependencies:
#  override: [script/ci-deps]
#  cache_directories: [vendor]

#test:
#  override:
#    - script/ci-run:
#        parallel: true
#
#deployment:
#  release:
#    tag: /v[0-9]+(\.[0-9]+)*/
#    commands:
#      - 'docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS'
#      - 'DOBI_EXEC_ID=release circle/dobi release'
